version:
  name: velociraptor
  version: 0.74.5
  commit: "049040963"
  build_time: "2025-07-03T16:15:07Z"
  compiler: go1.23.2
  system: windows
  architecture: amd64
Client:
  server_urls:
  - https://localhost:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIRAIs+cXgwa5q9ETq/YCBXSCkwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI1MDgyMjEyMTkxNVoXDTM1
    MDgyMDEyMTkxNVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnbCNbnozSh3j+Ms43pHAqc8XqnISCUhX
    URpld6+W2wdxzpvPSvSHZ+RRJipeDtTk1C8lrNrmE3EjBVK+/5fe0PZEJQd1O1+L
    a3XmHbn/en94Gnb0Q2AaVI3VFzyOGVVjQHb7pByJaQgN8u8ytdoJavidYOEkukbl
    SoB+Fcyi8HcJTaZnG6hbIoinv+uLTAUwLZFY/oNaoMsn2+K3xS39Om7qXBKcZaJx
    hYoiVOlB3u+WxXvQgDSrpkqKmd1yn3Ju/e+Aef9E5LPlmFckkrJwBOpalb2AH/uj
    1HL17xvFjNahM799ID5Fx5WcMdu5SFrktpjJZ9qPw8JSFZw64BVEVQIDAQABo4GM
    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUz/aWOu97PMW8ilz2gqZjB4PQ
    s4EwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
    KoZIhvcNAQELBQADggEBAC8hH3VbFtA6c7uaQQbkxSk/bdoJ8UzKI3OJHFOCDgw1
    U+3cXDpETrD7XHXrDkF+TBbps3tHoW8ldx4WBybJZ999nzXoeE77ySzfd1w/F6St
    HOTy/PHrD7erHqdlGZtQujBP/IOm+EooKh1YCZHGwdZoWNoLasp//H6D5z+0a8OU
    pp9JeiKkLIgbYs/g4My+qXX0yKzVMinocf5LdsZ1m7M+QRZzz5US+7jhywUiHHuv
    G4nFKKHaBCh/cEv828h3EFa3uAlTZP1jJxtF+zBWE1fTeRidkCAF7nAPGfAru7op
    Aq8UIK6LDMNhna8pQI0RjruWM80DEg8aM1NYvSALvK0=
    -----END CERTIFICATE-----
  nonce: tDklORzy9wg=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  server_version:
    version: 0.74.5
    commit: "049040963"
    build_time: "2025-07-03T16:15:07Z"
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  bind_address: 127.0.0.1
  bind_port: 8001
  bind_scheme: tcp
GUI:
  bind_address: 127.0.0.1
  bind_port: 8889
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQjCCAiqgAwIBAgIRAPKohTlRoNwzFKcDinTfQIQwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI1MDgyMjEyMTkxNVoXDTI2
    MDgyMjEyMTkxNVowKTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRAwDgYDVQQDDAdH
    UlBDX0dXMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmOiS0IRWO5ZD
    vi4xS03AIXyECMp63SfXD/hj13fHzsXJMqXKdy7IjVZXZHuch4EzAXLRBS4O1sxA
    JJVCstIA+clEemhVlPBitcic+RK2BSIzgFxlI4/ZsVBnzwm6C6/3IoHb8d/Q6BG4
    HjF+lmqjiwemYGjO+8JIJJoGFep7b5X6I+Fr0yuln1/rHth7GQWOit4cI5rCUUTQ
    VLaNPnUsTY96a7mCbM/bM55OlRxBF2tTNWkIv1oVWZgCxsb/J+32cTe5pGW+lRuc
    NVANQDchpYpnvzDKSrn1BIfX4SNBpVeB0RgTYuZB5rXWlQbCLhhBkR0rNBK3m7lF
    XfYEeR9tgQIDAQABo3QwcjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUz/aWOu97
    PMW8ilz2gqZjB4PQs4EwEgYDVR0RBAswCYIHR1JQQ19HVzANBgkqhkiG9w0BAQsF
    AAOCAQEAaMLTyQzPLfezpluXZInTuIf7J73D0Ove7xV3NdlKeDi/BRcUt790iwrI
    wTLTX1HouJweIbxyNB4GDAS39iOYeGc3LLeuENQiQFRnC9G4nviA5wIUOva79MbY
    W7vhzjk5e2dh08qg1oUtjJ4FOc4fOHuVIraY3c0ls+xftK5KTBKI89KQ3uVOfbj4
    bO343eP7oppslbbijzGkYZzyhDpOlgO2XN6rndNsF5r7mYpMKchneB9/8H4LauRE
    mJqYp5O3Yvb1dyUa9RCf4YjIW/wGvhH8fJ5l+rFsFd8caj+71+g1AsRS8GvtiVbf
    F1uKrt7LckF7M2CKEUajt8ZLcGqvVA==
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAmOiS0IRWO5ZDvi4xS03AIXyECMp63SfXD/hj13fHzsXJMqXK
    dy7IjVZXZHuch4EzAXLRBS4O1sxAJJVCstIA+clEemhVlPBitcic+RK2BSIzgFxl
    I4/ZsVBnzwm6C6/3IoHb8d/Q6BG4HjF+lmqjiwemYGjO+8JIJJoGFep7b5X6I+Fr
    0yuln1/rHth7GQWOit4cI5rCUUTQVLaNPnUsTY96a7mCbM/bM55OlRxBF2tTNWkI
    v1oVWZgCxsb/J+32cTe5pGW+lRucNVANQDchpYpnvzDKSrn1BIfX4SNBpVeB0RgT
    YuZB5rXWlQbCLhhBkR0rNBK3m7lFXfYEeR9tgQIDAQABAoIBABfq0QQSnxZk86Ws
    vgMkXzgdrN1fJoavM6GI3b0XPEaog0cLzbaEt9P7vGG4QAyl9d91ISKpSKLqgeH3
    At7LoGFxzOdEqJZKX3ZFsd/3wEbfSaT7TsqYNpnYlNQ6lkI7vPFF1KxpsNiL5Pu8
    DCvk9D3L7YdI/Y89nWE0Ql1tNu+GDRn4q3ccFOb3OXAO2D/pJ6WP0oA1mCDGc/1g
    2Y0TotpSreocPjSZmCp70KU83J7r/2NFiliAvH0IyJdxKcDJxJ72A/ev42Nrpue0
    BqQl/hkj16d9XL+wdzVb4F6rCOuQO+x8+Zg0XxJTxkGkRcdUkjDprWIjUPUi20rb
    se+UqUECgYEAwnqyfptlEHz0iDl0TEsVUFrG3VNXz1+DNVsiLQ7proR4+OTXrs42
    a5zmmWJ0Mqg8T8Tr45TotMeQNSVJXOgDqohGhliLUZ6EAHS6GkT7NwpkOwjc7o2a
    JAU1eHxZNsq1DoEieegIlp+DltxMfFlMldmL3jHqG3BwKIaSrsWmSOkCgYEAyUdk
    4fxGpQqKvhdOP6rdsutnIgsrvZFFOEj/j/YTsmFJPtqQNNgRUB7fL+or8XiIfA2Y
    zM9DhtXGofJ1vMW7wuOOm6qnraLUyNhP3aZiZNivO4m5njqCXPOOqiZYn+EGGzBe
    7y7yw7WbRYFGIxQYBpUVOgiPLCcx07O6BZSKoNkCgYB91GtW1W4/i8mftiTUFCR3
    ODTBEOKYrwCy7gMfyi1SGC45Q791P8EgQYVGKthpykYzioLhXgBur0xTxotADHIK
    zV9sHzANIBXiQaQDySwNQbD2LVbdFktsEN621SXX+LHK76yB2aps4kp+uozWS+Ts
    c7Q2kG8bT9WRsviHEiTzuQKBgQDIDa/VdRr6Gvo/aYaafUeQ96wwCA5XgjXcdaGd
    AqYdG9jjIfVGsKK0kZqfUw6OGJD/S7xdhHvHXl7ow8YF9DpkwCwTyJCUYk0/us/W
    q/ML7NpuQLs+60R7ApD/yNE5Rzz8dR1GedFMeAp2EMEXSHeAw1ivr6Yt6l753Z68
    wSDwMQKBgAIN4+h3HvxW/G18r3mGP7sgbgD70r1xTvsL1hmq7Y3wPfFZbPhqa6ji
    thCDpxaJbp4bepc9iSxANQlph2lmHefHtTH8IrRS68a0TYkH76XGool1G7AqPFc6
    S6cxTAli+w2vq/D52j8c1aiwB9vOpZoqQCQK9Uo0d+ubvmX6Qm+M
    -----END RSA PRIVATE KEY-----
  public_url: https://localhost:8889/
  links:
  - text: Documentation
    url: https://docs.velociraptor.app/
    icon_url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MyIgaGVpZ2h0PSI2MyIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIwIDAgNTMgNjMiPjxwYXRoIGQ9Ik0yNyAzYy0zIDItMTMgOC0yMyAxMGw2IDMyYTEwMyAxMDMgMCAwIDAgMTcgMTZsNi01IDExLTExIDYtMzJDMzkgMTEgMzAgNSAyNyAzeiIgZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PHBhdGggZD0iTTI2IDBDMjMgMiAxMiA4IDAgMTBjMSA3IDUgMzIgNyAzNWExMTMgMTEzIDAgMCAwIDE5IDE4bDctNiAxMi0xMmMyLTMgNi0yOCA4LTM1QzQwIDggMjkgMiAyNiAwWm0wIDU1LTYtNC04LTktNS0yNnYtMWwyLTFjOC0xIDE2LTYgMTYtNmwxLTEgMSAxczggNSAxNyA2bDEgMXYxcy0zIDIzLTUgMjZsLTggOWMtMiAyLTQgNC02IDR6IiBmaWxsPSIjYWIwMDAwIiBmaWxsLW9wYWNpdHk9IjEiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjxwYXRoIGQ9Ik0zOSAxOWExMzQ3IDEzNDcgMCAwIDEtMTMgMjZoLTJMMTQgMTloM2wyIDEgMSAxdjFhMjUwIDI1MCAwIDAgMSA2IDE3IDUyODkgNTI4OSAwIDAgMCA5LTIwaDR6IiBmaWxsPSIjMDAwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLWRhc2hhcnJheT0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9ImJ1dHQiIHN0cm9rZS1saW5lam9pbj0ibWl0ZXIiIHN0cm9rZS13aWR0aD0iMSIvPjwvc3ZnPg==
    type: sidebar
    new_tab: true
  initial_users:
  - name: test
    password_hash: 1a7305971f853d5b9d3edc170e0310e5ba5a03b58ebc9386d5b710cc99bf61c4
    password_salt: c7b1239690323a8a7a72b89b55bfdc549e43112a1bf8a392217e0ff52809c82b

  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAnbCNbnozSh3j+Ms43pHAqc8XqnISCUhXURpld6+W2wdxzpvP
    SvSHZ+RRJipeDtTk1C8lrNrmE3EjBVK+/5fe0PZEJQd1O1+La3XmHbn/en94Gnb0
    Q2AaVI3VFzyOGVVjQHb7pByJaQgN8u8ytdoJavidYOEkukblSoB+Fcyi8HcJTaZn
    G6hbIoinv+uLTAUwLZFY/oNaoMsn2+K3xS39Om7qXBKcZaJxhYoiVOlB3u+WxXvQ
    gDSrpkqKmd1yn3Ju/e+Aef9E5LPlmFckkrJwBOpalb2AH/uj1HL17xvFjNahM799
    ID5Fx5WcMdu5SFrktpjJZ9qPw8JSFZw64BVEVQIDAQABAoIBAEkMG0g9NXs1A4Eh
    6vM3g49mDql3dCF2sHQyjSR3Y6OM/ExgYxNu2TboTism3zFxr5sXSBWdxYzmEPoL
    Tc0q9h3IpuKcZNMfPH+IOxQ0MEP3vpRL3HVFlIzssvSzqYPUyUh4lbN9QK41+/g4
    lD4nhctW5diWEyRzaQ4tHbtNc4F+eLDROzi6MiSjUXoTEBR+N09rwajEpVpbP+RY
    siYdR9vsa0CeCSB516TrIe1IOha0GNOl1Fvy4O7gbCUxa3A1PSkoKA0QWtQSGYg1
    8xLPK+a7nKizcH95i0+xa73qOXSMnGc89Z8MwXJqwpYUoDDNPF3pJjPyypAxJjTC
    ABymNQECgYEA0aPZd8+4mlf5Gvna5BcLPAceW4dvJWkPTr3NDj/HGELoaybFLuDM
    4JSEGIMP+Zcz93pXz6800ImCVKt2wucUo86Y680+laV6BVIyPHkovA1sXriFsLQd
    G1i1Hfmynms2sQvDMaVV5886HA9Nur0RxC2+Z7z/hMljTpibhOaXy5UCgYEAwI+v
    m0BBDRspk1spoxql2bE6vsHYv/TVkscS6t++SczUZOg8cEnxRAO2M5LXIytwx621
    zL1XaSigavl1rq+mZM2yTGpeg+JEg0DYM/FqE034gxnJi9G/3cADQ5qpSWk7e6ez
    MgFzyNutT9gEx5PzWd2LQlTpk3lMZmBJ43ZHZcECgYAlxK4mLq8kZ1sCqCbuVtR4
    URQAC2tTwxS16+3odkcJMOyseUSnCGsAvuD5hYs4PSxolosBaKBMPanUVTvFK1qF
    lG/qc4Sl8zUDhmZ0jKNxFb4DZpz3U8u2pImkx9qNPeWRifv1ksLiS2w9p+gqD2wG
    +vLFv8ANDTct7sJ99Ak+7QKBgE+lXsoFOqLUIE8tvrwS0pSHJLgv75n+B7SNGLsD
    Tm6yBQuzrwP24Y7zRhJw4wFN/3jn1bFYg2YggrGcetuFFXrORbgrquo71YDAemyJ
    pwlTD74SFXX6jLSIrhDxUKHnn83WoFzHkv96NWY4AEoYXOhHpUkLXA0+d6ZEn2sw
    yflBAoGAEKsD3kO3IMavDc/s/8V+KjdmXXAlU3yc3VsPM4wbbfh8ft14gN2vvxDs
    11WQLMM5EKg8uTlzCxEyuzeNSyX8pdXdhTrEJdAfbVoTCxv9hevTXyqeQE6tRU//
    CkD391k/gXtUaribs/Xcr2hz3Ro/TQ1tcVZOIt70lHN3Rybb6OU=
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: localhost
  bind_address: 0.0.0.0
  bind_port: 8000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDVzCCAj+gAwIBAgIQeMsDCGZUg4k4SBpYU7lmGzANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjUwODIyMTIxOTE1WhcNMjYw
    ODIyMTIxOTE1WjA0MRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMTElZl
    bG9jaXJhcHRvclNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    AOb2q4EkZ4uOuczBYcJIj6KNclH5R6/6jmh6jdItIoMGjXx+8AaARBiVhi/7LT3o
    mt/VOA52XLzZqrwDJlAk03YMKwy7D6szQQdXzreJunRg0mzjCyWuFC1xMvhXdAJT
    uEXYw6wtBnN4fV3eoFHa15ozIwo3PDqKTGhJ7HAnQz9Uxi4HUGVuKelGDOEtlOEl
    oJ7diLXMk7SO6t7wr/A2D/0IZDTZxAL0EvJbRdUY8SACR9zbbDUCbcV0v9A0V3wD
    nOuUz1xatclGLW9R3W18O/pQAEIOcHHWChfNjSZjfzViv5CD9nl5wOx/0NVkoSmV
    rrPlaPNqglMCkI9B085Kxj8CAwEAAaN/MH0wDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
    MBaAFM/2ljrvezzFvIpc9oKmYweD0LOBMB0GA1UdEQQWMBSCElZlbG9jaXJhcHRv
    clNlcnZlcjANBgkqhkiG9w0BAQsFAAOCAQEAZXiL/nYk39oZIj0QfMaO/yLFEy13
    t/Spe1w1KpJjQXzjJUQxKCO60262S2LNrJIwpOx1cko+GuNkF8Dsuytt26EV3xVm
    G+Xp03lBnFqqCbGmBm4Oh0LRogz2oPWLXew40jSGK6ye1LUnKrX/fPx/rVDEFXiY
    ldTuALf0Ux2cEPN7dL5350AVlCPCuMuP0ZhwymXDP3wQ7TUCnmwQLrjsNzNKJEjn
    FXQDS8yUI4QJT/nhm7ku0csLiHcJrVTnEF+Aeiy0k69WA7lcjA1tvwTPwBA7zcHL
    uiHR8UZMdKF2V+TnYQ8bHzxileqNqxMWI0ZO56oh7m2m4AvISdn+Ojp/lQ==
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA5vargSRni465zMFhwkiPoo1yUflHr/qOaHqN0i0igwaNfH7w
    BoBEGJWGL/stPeia39U4DnZcvNmqvAMmUCTTdgwrDLsPqzNBB1fOt4m6dGDSbOML
    Ja4ULXEy+Fd0AlO4RdjDrC0Gc3h9Xd6gUdrXmjMjCjc8OopMaEnscCdDP1TGLgdQ
    ZW4p6UYM4S2U4SWgnt2ItcyTtI7q3vCv8DYP/QhkNNnEAvQS8ltF1RjxIAJH3Nts
    NQJtxXS/0DRXfAOc65TPXFq1yUYtb1HdbXw7+lAAQg5wcdYKF82NJmN/NWK/kIP2
    eXnA7H/Q1WShKZWus+Vo82qCUwKQj0HTzkrGPwIDAQABAoIBAQDg6Z0h6Z2b3aU5
    q6fTVm3pUezdvu78g/Zh79ZjsehFx//IGKUM76NgfVtrJiJsgzMufahVDRZKIX2O
    EVMiAHqcHkVd5Fvhz8unpu569PhJlG/V8VNNojOr/OwxwpgKHBT6j5gc9sutbsxG
    uSFOFNqYIuwgaqGQMFUvya0hmlp2M/IasHhf8Y/txIa0RVIHAA4LggxB+jbLCKUR
    991wUFWFubLAF+uyMVJSdojeqUqk7G1q66aZlM2wYmNMIr4zz8txasSUzs7XUH3c
    T2HUPbAGkdsISIg2GZgHtj+2rLXE1UvgqocriWVYVjtcy9O1gMpFfp9VRfjJo4m1
    MVIqKDmhAoGBAPA1sTz2OyNOVrkFSp5iZg5e6Zyk3aNO0ICu5qZGQmPeA8t9/xpD
    GsJqimh08Wut2T5BOUNpvAJYkDQYpaXvl2w+0xDd03g7om4/c/kTCDMgn3kk/7NF
    isGx8Ol/xkzc/1rPBkoSExVpAHhX7gU8JaN5xtTLxo7wk3xWZ9FdCLJbAoGBAPYl
    YXCK5sellkZ1Qwgo1ZjYmxTJ4CiM5WuKf3VXjZHhDgd3cvr2HAMY/R6wxcDJuOeg
    gcIVkQAUJZgPyAeKR9W556qyPoJg3EDHvrUuos4XkW0IFp15LNITbc1EqCdZIU0E
    Z836Y2CPVydhPkGvMlXPyOkVBdmNrJk/0a9IWXjtAoGBAIL9JIuT0qfsHkqC4jAA
    hJqtk0MCfIKDhhvGRKzDf4yqEvOy35vYoA0IwDU6IDSR9veF5c4nKIk29lwSXLJi
    NvamQ77c2GamTmtEWt+mS0BmN9B+JpoCACqj+DW8ocxkbzN71Xgq5xEz0zfM61Ub
    eYLt80kzXjGwaxzQmYiH7SglAoGBAKdcIzRyPRfh7ptZf4o8uX6DSG6KFG993T+R
    m7gdH5TggLly7irUy5cPlosXhl3eymozKAbewwhaqnUJxefajZ00GeBl8TqUwS0K
    oxBt9SRLwgVwSnAnw+HSdAXteKfIYmwLYskaRheRXqDX7Yyboo3WCbTxJlkVixVn
    3xpfBvbBAoGACw0EaigUOQ1vPaQ1TUhaIITWvZ8j8+Ovns5QCBIYMAakqYDSc6f/
    xzR4SUnEMcOovWOjxbpk2nzVyAVJgCCMt6xxszCMpawvuZzx5fjW/jfiajb5LeTu
    HSEV22DXXzvmQD29x/GPKTriQZCFdG11Dj5dmEKa9qIO0nMDWd+6jBQ=
    -----END RSA PRIVATE KEY-----
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 10485760
    expected_clients: 30000
Datastore:
  implementation: FileBaseDataStore
  location: C:\Windows\Temp
  filestore_directory: C:\Windows\Temp
Logging:
  output_directory: C:\Windows\Temp/logs
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
obfuscation_nonce: vEtG6QjZclc=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
  certificate_validity_days: 365
